# Generated by Django 2.2.1 on 2019-05-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_employed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
